site_name: GDPRX - a toolkit to help with GDPR Compliance
repo_url: https://github.com/systopia/de.systopia.gdprx
site_description: 'A toolkit to help with GDPR Compliance.'
site_author: 'SYSTOPIA'
theme: 
  name: material

nav:
  - 'Introduction': index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en